name: Release
on:
  push:
    tags: ["v*.*.*"]
#  pull_request:
#    branches: [ stabilization* ]
jobs:
  validate-ubuntu:
    name: Release on Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Install Deps
        uses: mstksg/get-package@master
        with:
          apt-get: cmake ninja-build libopenscap8 libxml2-utils expat xsltproc python3-jinja2 python3-yaml ansible-lint python3-github
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: cmake ..
        working-directory: ./build
#      - name: Build All
#        run: make -j2 all
#        working-directory: ./build
#      - name: Build ZIP
#        run: make -j2 zipfile
#        working-directory: ./build
#      - name: Test
#        run: ctest -j2 --output-on-failure -E linkchecker
#        working-directory: ./build
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: .github/workflows/release-changelog.json
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: True
#          fail_on_unmatched_files: True
          body: ${{ steps.build_changelog.outputs.changelog }}
#          files: |
#            build/zipfile/scap-security-guide-*.zip
          files: LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
